//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanHang.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebsiteBanHangEntities : DbContext
    {
        public WebsiteBanHangEntities()
            : base("name=WebsiteBanHangEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<dbBrand> dbBrands { get; set; }
        public DbSet<dbCategory> dbCategories { get; set; }
        public DbSet<dbOder> dbOders { get; set; }
        public DbSet<dbProduct> dbProducts { get; set; }
        public DbSet<dbUsẻ> dbUsẻ { get; set; }
        public DbSet<dbOderDetail> dbOderDetails { get; set; }
    }
}
